# playbooks/yaml/argocd-apps/longhorn/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

patches:
  - path: patches/csi-plugin-resources.yaml
    target:
      kind: DaemonSet
      name: longhorn-csi-plugin

  - path: patches/ui-resources.yaml
    target:
      kind: Deployment
      name: longhorn-ui

  - path: patches/manager-resources.yaml
    target:
      kind: DaemonSet
      name: longhorn-manager

  - path: patches/driver-resources.yaml
    target:
      kind: Deployment
      name: longhorn-driver-deployer

  - path: patches/csi-attacher-resources.yaml
    target:
      kind: Deployment
      name: csi-attacher

  - path: patches/csi-provisioner-resources.yaml
    target:
      kind: Deployment
      name: csi-provisioner

  - path: patches/csi-resizer-resources.yaml
    target:
      kind: Deployment
      name: csi-resizer

  - path: patches/csi-snapshotter-resources.yaml
    target:
      kind: Deployment
      name: csi-snapshotter
