# playbooks/yaml/argocd-apps/longhorn/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.8.0
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: values.yaml

resources:
  - setting-default-data-path.yaml
  - storageclass-rwx.yaml

patches:
  - target:
      kind: DaemonSet
      name: longhorn-manager
    patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: longhorn-manager
      spec:
        template:
          spec:
            containers:
            - name: longhorn-manager
              resources:
                limits:
                  cpu: 500m
                  memory: 500Mi
                requests:
                  cpu: 100m
                  memory: 100Mi

  - target:
      kind: Deployment
      name: longhorn-driver-deployer
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: longhorn-driver-deployer
      spec:
        template:
          spec:
            containers:
            - name: longhorn-driver-deployer
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 128Mi

  - target:
      kind: Deployment
      name: longhorn-ui
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: longhorn-ui
      spec:
        template:
          spec:
            containers:
            - name: longhorn-ui
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 128Mi
