# playbooks/yaml/argocd-apps/longhorn/longhorn-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kpoxo6op/soyspray.git
    targetRevision: "v1.8.0"
    path: playbooks/yaml/argocd-apps/longhorn
    kustomize:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    # automated: # Comment out this block to disable auto-sync
    #   prune: true # Comment out
    #   selfHeal: true # Comment out
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
