apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: "https://charts.longhorn.io"
      chart: longhorn
      targetRevision: "1.7.2"
      helm:
        valueFiles:
          - $values/playbooks/yaml/argocd-apps/longhorn/values.yaml
    - repoURL: "https://github.com/kpoxo6op/soyspray.git"
      targetRevision: "v1.4.0"
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
