apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://charts.longhorn.io"
      chart: longhorn
      targetRevision: "1.8.0"
      helm:
        valueFiles:
          - $values/playbooks/yaml/argocd-apps/longhorn/values.yaml
    - repoURL: "https://github.com/kpoxo6op/soyspray.git"
      targetRevision: "v1.7.5"
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    # disable autsync while debugging
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
