persistence:
  defaultClass: true
  defaultClassReplicaCount: 1
  defaultDataLocality: best-effort
  migratable: true
  metricsPort: 9500

defaultSettings:
  defaultDataPath: "/storage"
  createDefaultDiskLabeledNodes: false
  defaultDataLocality: "disabled"
  deletingConfirmationFlag: true
  orphanAutoDeletion: true
  # Allow 30 minutes for volume operations to timeout (default: 90)
  backupstorePollInterval: 300

longhornUI:
  replicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

longhornManager:
  priorityClass: longhorn-critical
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 250m
      memory: 256Mi
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 5
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 5

longhornDriver:
  priorityClass: longhorn-critical
  resources:
    limits:
      cpu: 300m
      memory: 350Mi
    requests:
      cpu: 150m
      memory: 180Mi

instanceManager:
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

engineImage:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 45
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 5
  readinessProbe:
    initialDelaySeconds: 45
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 5

preUpgradeChecker:
  jobEnabled: false
  upgradeVersionCheck: false

csi:
  attacher:
    resources:
      limits:
        cpu: 250m
        memory: 320Mi
      requests:
        cpu: 100m
        memory: 128Mi
  provisioner:
    resources:
      limits:
        cpu: 250m
        memory: 320Mi
      requests:
        cpu: 100m
        memory: 128Mi
  resizer:
    resources:
      limits:
        cpu: 250m
        memory: 320Mi
      requests:
        cpu: 100m
        memory: 128Mi
  snapshotter:
    resources:
      limits:
        cpu: 250m
        memory: 320Mi
      requests:
        cpu: 100m
        memory: 128Mi
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

# Sets priority above system-node-critical
priorityClass:
  create: true
  name: longhorn-critical
  value: 2000001001

service:
  ui:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.127
    nodePort: null
  manager:
    type: ClusterIP
    nodePort: ""
    ports:
      manager: 9500
      metrics: 9500

metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
    port: manager
    interval: 60s
    scrapeTimeout: 30s
