apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitoring-lifecycle-probe
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: monitoring-lifecycle-probe
      interval: 1m
      rules:
        - record: soyspray_config_lifecycle_probe
          expr: vector(1)
