import type { Language } from "./lib/state";

export const uiCopy = {
  en: {
    siteName: "Detailed autism questionnaire",
    languageButton: "Русский",
    themeLabel: "Theme",
    themeAuto: "Auto",
    themeLight: "Light",
    themeDark: "Dark",
    introTitle: "A quieter way to notice patterns",
    introBody:
      "This experience looks for patterns across communication, relationships, masking, repetition, routine, interests, sensory processing, daily capacity, and childhood history.",
    privacyNote:
      "Your answers and score stay only in this browser tab. They are not transmitted or retained and disappear when you refresh or close the page. Cloudflare may process connection metadata to deliver the site.",
    versionOne: "v1 - mediocrity AI created because I did not ask to adhere to my vision.",
    versionTwo:
      "v2 - 328 detailed questions drawn from 30 captioned videos. Minimal AI rewriting. Simpler design.",
    questionSetLabel: "Choose a length",
    versionOneChoice: "Short",
    versionTwoChoice: "Full",
    versionOneTitle: "Short · 50 questions",
    versionTwoTitle: "Full · 328 questions",
    startVersionOne: "Start short",
    startVersionTwo: "Start full",
    versionInfo: "Version info",
    versionTitle: "Version 2.1.0",
    backToAssessment: "Back to the assessment",
    seeSources: "See the sources",
    resume: "Resume assessment",
    sourcesTitle: "Thirty caption-backed perspectives",
    sourcesBody:
      "I asked Codex to collect, read, translate, deduplicate, and compile autistic traits from 30 quality-filtered videos.",
    sourceBalance:
      "The collection combines lived-experience creators, clinicians, hospitals, professional bodies, charities, and institutional sources. These sources do not carry equal evidentiary weight.",
    qualityNote:
      "Quality-filtered means relevant, usable, caption-backed, and deliberately varied. It does not mean clinically validated or ranked only by views.",
    languagesTitle: "Languages represented",
    representedLanguages: ["English", "Russian", "Brazilian Portuguese", "Korean"],
    translated: "Non-English material translated into English",
    processedLanguages: "Processed assessment content: English and Russian",
    sourceType: "Source type",
    originalLanguage: "Original language",
    captionBasis: "Caption basis",
    openSource: "Open source",
    startAssessment: "Start the assessment",
    section: "Section",
    answered: "answered",
    responsePrompt:
      "How strongly and consistently does each statement describe you across your life and in different settings?",
    childhoodPrompt:
      "Think about the period before age 12. Use “I don't know” or “Not applicable” when that is the most accurate answer.",
    scale: ["Not at all", "A little", "Sometimes", "Often", "Very strongly"],
    unknown: "I don't know",
    notApplicable: "Not applicable",
    back: "Back",
    continue: "Continue",
    shortcut: "Keyboard: Alt + Left or Right Arrow",
    startOver: "Start over",
    confirmStartOver: "Confirm start over",
    cancel: "Cancel",
    startOverPrompt: "Clear all answers and return to the first page?",
    completeTitle: "Ready to reveal",
    completeBody:
      "Your answers are complete. Nothing has been calculated or shown on screen until you choose the button below.",
    reviewBeforeReveal: "Review answers",
    reveal: "Reveal my result",
    scoreLabel: "Custom trait-resonance score",
    outOfHundred: "out of 100",
    continuumLabel: "Full trait-resonance continuum",
    bands: ["Almost none", "Low", "Moderate", "High", "Very high"],
    breakdownTitle: "Areas of resonance",
    strongest: "The strongest area of resonance in your answers is",
    weakest: "The weakest area of resonance in your answers is",
    maskingContext: "Masking and hidden effort",
    childhoodContext: "Childhood history",
    impactContext: "Functional impact",
    noChildhood:
      "Childhood answers were unavailable, so they did not lower or enter the combined score.",
    contextScore: "Separate context score",
    reviewAnswers: "Review answers",
    retake: "Retake assessment",
    confirmRetake: "Confirm retake",
    retakePrompt: "Clear these answers and begin a new assessment?",
    methodology: "Methodology and provenance",
    methodSummary:
      "This is an original, deterministic estimate. It is not a validated psychometric instrument.",
    weightingTitle: "Domain weighting",
    weightingBody:
      "Each section is normalized before combination, so longer sections do not dominate. Core social, repetitive, routine, interest, and sensory areas carry more influence than general daily impact. Missing childhood answers are removed from the relevant denominator.",
    bandsTitle: "Interpretation bands",
    bandsBody:
      "The five bands divide this custom 0–100 continuum into broad descriptive ranges. They are not clinical cutoffs, population percentiles, diagnostic probabilities, or levels of support need.",
    provenanceTitle: "Question provenance",
    guidanceTitle: "Official and primary cross-checks",
    instrumentsTitle: "Established instruments reviewed",
    instrumentsBody:
      "No established questionnaire is reproduced or scored here. Each review remains separate from the custom estimate.",
    imageCreditsTitle: "Image credits",
    sourcesForQuestion: "Sources",
    imageCredit: "Artwork",
  },
  ru: {
    siteName: "Подробный опрос об аутизме",
    languageButton: "English",
    themeLabel: "Тема",
    themeAuto: "Авто",
    themeLight: "Светлая",
    themeDark: "Тёмная",
    introTitle: "Спокойный способ заметить закономерности",
    introBody:
      "Этот опрос помогает увидеть закономерности в общении, отношениях, маскинге, повторениях, распорядке, интересах, сенсорном восприятии, повседневных возможностях и детском опыте.",
    privacyNote:
      "Ваши ответы и результат остаются только в памяти этой вкладки браузера. Они не передаются и не сохраняются и исчезают после обновления или закрытия страницы. Cloudflare может обрабатывать метаданные соединения для доставки сайта.",
    versionOne:
      "v1 — посредственный результат ИИ, потому что я не попросил ИИ следовать моему замыслу.",
    versionTwo:
      "v2 — 328 подробных вопросов по 30 видео с субтитрами. Минимум ИИ-редактирования. Более простой дизайн.",
    questionSetLabel: "Выберите длину",
    versionOneChoice: "Короткий",
    versionTwoChoice: "Полный",
    versionOneTitle: "Короткий · 50 вопросов",
    versionTwoTitle: "Полный · 328 вопросов",
    startVersionOne: "Начать короткий",
    startVersionTwo: "Начать полный",
    versionInfo: "Сведения о версии",
    versionTitle: "Версия 2.1.0",
    backToAssessment: "Назад к опросу",
    seeSources: "Посмотреть источники",
    resume: "Продолжить опрос",
    sourcesTitle: "Тридцать точек зрения на основе субтитров",
    sourcesBody:
      "Я попросил Codex собрать, прочитать, перевести, объединить и убрать повторы в описаниях аутистических особенностей из 30 видео, прошедших отбор по качеству.",
    sourceBalance:
      "В подборке есть авторы с личным опытом, клиницисты, больницы, профессиональные организации, благотворительные и научные учреждения. Доказательная ценность этих источников неодинакова.",
    qualityNote:
      "Отбор по качеству означает релевантность, пригодные субтитры и намеренное разнообразие. Это не клиническая валидация и не рейтинг только по просмотрам.",
    languagesTitle: "Представленные языки",
    representedLanguages: ["Английский", "Русский", "Бразильский португальский", "Корейский"],
    translated: "Неанглоязычные материалы переведены на английский",
    processedLanguages: "Содержание опроса доступно на английском и русском",
    sourceType: "Тип источника",
    originalLanguage: "Язык оригинала",
    captionBasis: "Основа субтитров",
    openSource: "Открыть источник",
    startAssessment: "Начать опрос",
    section: "Раздел",
    answered: "отвечено",
    responsePrompt:
      "Насколько сильно и постоянно каждое утверждение описывает вас на протяжении жизни и в разных ситуациях?",
    childhoodPrompt:
      "Вспомните период до 12 лет. Выберите «Я не знаю» или «Не применимо», если это самый точный ответ.",
    scale: ["Совсем нет", "Немного", "Иногда", "Часто", "Очень сильно"],
    unknown: "Я не знаю",
    notApplicable: "Не применимо",
    back: "Назад",
    continue: "Продолжить",
    shortcut: "Клавиатура: Alt + стрелка влево или вправо",
    startOver: "Начать заново",
    confirmStartOver: "Подтвердить начало заново",
    cancel: "Отмена",
    startOverPrompt: "Удалить все ответы и вернуться на первую страницу?",
    completeTitle: "Результат готов к показу",
    completeBody:
      "Все ответы заполнены. До нажатия кнопки ниже результат не вычисляется и не показывается на экране.",
    reviewBeforeReveal: "Проверить ответы",
    reveal: "Показать мой результат",
    scoreLabel: "Пользовательская оценка близости особенностей",
    outOfHundred: "из 100",
    continuumLabel: "Полная шкала близости особенностей",
    bands: ["Почти нет", "Низкая", "Умеренная", "Высокая", "Очень высокая"],
    breakdownTitle: "Области близости",
    strongest: "Самая сильная область близости в ваших ответах —",
    weakest: "Самая слабая область близости в ваших ответах —",
    maskingContext: "Маскинг и скрытые усилия",
    childhoodContext: "Детский опыт",
    impactContext: "Влияние на повседневную жизнь",
    noChildhood:
      "Данных о детстве недостаточно, поэтому они не снизили и не вошли в общий результат.",
    contextScore: "Отдельная контекстная оценка",
    reviewAnswers: "Проверить ответы",
    retake: "Пройти опрос снова",
    confirmRetake: "Подтвердить повторный опрос",
    retakePrompt: "Удалить эти ответы и начать новый опрос?",
    methodology: "Методика и происхождение",
    methodSummary:
      "Это оригинальная детерминированная оценка, а не валидированный психометрический инструмент.",
    weightingTitle: "Вес областей",
    weightingBody:
      "Перед объединением каждый раздел нормализуется, поэтому длинные разделы не доминируют. Основные социальные, повторяющиеся, сенсорные особенности, распорядок и интересы влияют сильнее, чем общее повседневное влияние. Недоступные ответы о детстве исключаются из соответствующего знаменателя.",
    bandsTitle: "Интерпретация диапазонов",
    bandsBody:
      "Пять диапазонов делят пользовательскую шкалу 0–100 на широкие описательные части. Это не клинические пороги, популяционные процентили, вероятность диагноза или уровень потребности в поддержке.",
    provenanceTitle: "Происхождение вопросов",
    guidanceTitle: "Официальные и первичные материалы для сверки",
    instrumentsTitle: "Проверенные стандартизированные инструменты",
    instrumentsBody:
      "Здесь не воспроизводится и не оценивается ни один стандартизированный опросник. Их проверка отделена от пользовательской оценки.",
    imageCreditsTitle: "Сведения об изображениях",
    sourcesForQuestion: "Источники",
    imageCredit: "Произведение",
  },
} satisfies Record<Language, Record<string, string | string[]>>;
