# File: playbooks/yaml/argocd-apps/pihole/configmaps/custom-dns-configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-dns-configmap
  namespace: pihole
data:
  custom.list: |
    192.168.1.120 podinfo.test.soyspray.vip
    192.168.1.127 longhorn.lan
    192.168.1.126 alertmanager.lan
    192.168.1.125 prometheus.lan
    192.168.1.123 grafana.lan
    192.168.1.122 pihole.lan
    192.168.1.121 argocd.lan
    192.168.1.100 flask.lan
