apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: pihole
    version: 2.26.1
    repo: https://mojo2600.github.io/pihole-kubernetes
    releaseName: pihole
    valuesFile: values.yaml

resources:
  - custom-dns-configmap.yaml
  - ftl-configmap.yaml
