# playbooks/yaml/argocd-apps/pihole/values.yaml
webHttp: "80"
webHttps: "443"

replicaCount: 1
strategyType: RollingUpdate
hostNetwork: false
hostname: ""
virtualHost: "pi.hole"
privileged: false

persistentVolumeClaim:
  enabled: true
  storageClass: longhorn
  size: 500Mi
  accessModes:
    - ReadWriteOnce

extraVolumes:
  dnsmasq-conf:
    configMap:
      name: custom-dns-configmap

extraVolumeMounts:
  dnsmasq-conf:
    mountPath: /etc/pihole/custom.list
    subPath: custom.list

extraEnvVars:
  DNSMASQ_LISTENING: all

serviceWeb:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.124
  type: LoadBalancer
  http:
    enabled: true
    port: 80
  https:
    enabled: false
    port: 443

serviceDns:
  externalTrafficPolicy: Cluster
  mixedService: true
  loadBalancerIP: 192.168.1.122
  type: LoadBalancer
  port: 53

serviceDhcp:
  enabled: false
  type: ClusterIP
  port: 67
  externalTrafficPolicy: Cluster

dualStack:
  enabled: false

doh:
  enabled: false

monitoring:
  sidecar:
    enabled: false
    image:
      repository: prom/prometheus
      tag: latest
      pullPolicy: IfNotPresent
    port: 9100
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  podMonitor:
    enabled: false
    namespace: ""
    interval: 30s
    bearerTokenFile: ""
    bearerTokenSecret:
      name: ""
      key: ""

ingress:
  enabled: false
  hosts: []
  path: /
  annotations: {}
  tls: []
  ingressClassName: ""

podDisruptionBudget:
  enabled: false

antiaff:
  enabled: false

podDnsConfig:
  enabled: false

dnsmasq:
  staticDhcpEntries: []
  upstreamServers: []
  customDnsEntries: []
  customSettings:
    - bind-interfaces
    - listen-address=0.0.0.0
  additionalHostsEntries: []
  customCnameEntries: []

admin:
  enabled: true
  existingSecret: ""
  passwordKey: "password"
  adminPassword: "adminpassword"

dnsHostPort:
  enabled: false
  port: 53

image:
  repository: pihole/pihole
  tag: 2024.07.0
  pullPolicy: IfNotPresent

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false

# https://firebog.net/
adlists:
  # Suspicious Lists
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
  - https://v.firebog.net/hosts/static/w3kbl.txt
  # Advertising Lists
  - https://adaway.org/hosts.txt
  - https://v.firebog.net/hosts/AdguardDNS.txt
  - https://v.firebog.net/hosts/Admiral.txt
  - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
  - https://v.firebog.net/hosts/Easylist.txt
  - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
  - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
  # Tracking & Telemetry Lists
  - https://v.firebog.net/hosts/Easyprivacy.txt
  - https://v.firebog.net/hosts/Prigent-Ads.txt
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
  - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
  - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
  # Malicious Lists
  - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
  - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
  - https://v.firebog.net/hosts/Prigent-Crypto.txt
  - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
  - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
  - https://phishing.army/download/phishing_army_blocklist_extended.txt
  - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
  - https://v.firebog.net/hosts/RPiList-Malware.txt
  - https://v.firebog.net/hosts/RPiList-Phishing.txt
  - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
  - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
  - https://urlhaus.abuse.ch/downloads/hostfile/
  # Other Lists
  - https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
