apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boys-data
  labels:
    app.kubernetes.io/name: boys
    app.kubernetes.io/part-of: boys
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
