#playbooks/yaml/argocd-apps/radarr/deployment.yaml
#------------------------------------------------------------------------------
# • Image: linuxserver/radarr:5.21.1.9799‑ls268  ← latest stable (non‑nightly)
# • Namespace: media  (keeps all torrent‑stack services together)
# • Minimal resources; tweak after observing Grafana.
#------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  labels:
    app: radarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:5.21.1.9799-ls268
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7878
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Pacific/Auckland"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config
