#playbooks/yaml/argocd-apps/radarr/pvc-config.yaml
#------------------------------------------------------------------------------
# Stores Radarr's /config so settings survive pod restarts.
# • Longhorn RWO 1 Gi matches Jackett pattern.
# • Use a dedicated claim instead of re‑using qBittorrent's downloads PVC;
#   Radarr needs only its DB & metadata here.
#------------------------------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
