#playbooks/yaml/argocd-apps/radarr/radarr-application.yaml
#------------------------------------------------------------------------------
# Targets the "torrent" branch just like Jackett & qBittorrent.
#------------------------------------------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kpoxo6op/soyspray.git
    targetRevision: "v1.11.1"
    path: playbooks/yaml/argocd-apps/radarr
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
