#playbooks/yaml/argocd-apps/radarr/service.yaml
#------------------------------------------------------------------------------
# LoadBalancer with fixed IP for consistency in local‑DNS records.
#------------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
  labels:
    app: radarr
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.130
  ports:
    - port: 7878
      targetPort: 7878
      protocol: TCP
      name: http
  selector:
    app: radarr
