apiVersion: v1
kind: PersistentVolume
metadata:
  name: memes-vk-archive
  labels:
    app.kubernetes.io/name: memes
    app.kubernetes.io/part-of: memes
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /srv/media/downloads/vk
  claimRef:
    namespace: memes
    name: memes-vk-archive
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-0
