apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memes-data
  labels:
    app.kubernetes.io/name: memes
    app.kubernetes.io/part-of: memes
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    argocd.argoproj.io/sync-wave: '-3'
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
