# Post-import Job for Calibre Web
# - Imports or merges every file under /books into /books/Calibre_Library
# - Fixes ownership on both the library and /config
# - Enables anonymous browsing and ensures Guest has role 290
# - Deletes itself 24 h after completion (ttlSecondsAfterFinished)
apiVersion: batch/v1
kind: Job
metadata:
  name: calibre-web-import
  namespace: media
spec:
  ttlSecondsAfterFinished: 86400
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: calibre-import
        image: linuxserver/calibre:8.3.0
        imagePullPolicy: IfNotPresent
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Pacific/Auckland"
        volumeMounts:
          - name: config
            mountPath: /config
          - name: books
            mountPath: /books
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -eux

            LIB="/books/Calibre_Library"
            mkdir -p "$LIB"
            calibredb add -r /books --with-library "$LIB" --recurse
            chown -R 1000:1000 "$LIB" /config

            DB=/config/app.db
            for i in $(seq 1 60); do [ -f "$DB" ] && break; sleep 3; done
            [ -f "$DB" ] || exit 0

            python3 - <<'PY'
            import os, sqlite3, sys

            db = "/config/app.db"
            if not os.path.exists(db):
                sys.exit(0)

            con = sqlite3.connect(db)
            con.execute("UPDATE settings SET config_anonbrowse = 1;")
            con.execute(
                "INSERT OR IGNORE INTO user (name,password,role) "
                "VALUES ('Guest','',290);"
            )
            con.execute(
                "UPDATE user SET role = 290 WHERE name = 'Guest';"
            )
            con.execute(
                "UPDATE settings SET config_calibre_dir = '/books/Calibre_Library';"
            )
            con.commit()
            con.close()
            PY
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: calibre-web-config
        - name: books
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
