# playbooks/yaml/argocd-apps/calibre-web/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc-config.yaml
  - service.yaml
  - ingress.yaml
  - deployment.yaml
  - job-calibre-web-poststart.yaml

# -patches:
