# playbooks/yaml/argocd-apps/calibre-web/pvc-config.yaml

# A small 1Gi PersistentVolumeClaim for Calibre Web config data.
# We store user settings and metadata here.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-rwx
  resources:
    requests:
      storage: 1Gi
