# playbooks/argocd/apps/external-dns/values.yaml
provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token

domainFilters:
  - soyspray.vip

policy: upsert-only
registry: txt
txtOwnerId: k8s

sources:
  - ingress

extraArgs:
  - --txt-prefix=external-dns-
  - --ignore-ingress-tls-spec
  - --ignore-ingress-rules-spec
