apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gi-data
  labels:
    app.kubernetes.io/name: gi
    app.kubernetes.io/part-of: gi
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gi-backups
  labels:
    app.kubernetes.io/name: gi
    app.kubernetes.io/part-of: gi
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
