apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-reflector
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reflector
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
    verbs:
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-reflector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reflector
subjects:
  - kind: ServiceAccount
    name: secret-reflector
    namespace: cert-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-reflector
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: secret-reflector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-reflector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secret-reflector
    spec:
      serviceAccountName: secret-reflector
      containers:
        - name: secret-reflector
          image: ghcr.io/emberstack/kubernetes-reflector:10.0.3
          imagePullPolicy: IfNotPresent
          args:
            - --enable-leader-election=true
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 128Mi
