# playbooks/yaml/argocd-apps/prometheus/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    version: 65.5.0
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    valuesFile: values.yaml

configMapGenerator:
  - name: grafana-dashboard-pihole
    files:
      - pihole-dashboard.json=dashboards/pihole-dashboard.json

resources:
  - custom-prometheus-rules.yaml
  - additional-scrape-configs.yaml

patchesStrategicMerge:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: grafana-dashboard-pihole
      labels:
        grafana_dashboard: "1"