# playbooks/yaml/argocd-apps/prometheus/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    version: 65.5.0
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    valuesFile: values.yaml

resources:
  - custom-prometheus-rules.yaml
  - dashboards/grafana-dashboard-pihole.yaml
