# playbooks/yaml/argocd-apps/prometheus/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kube-prometheus-stack
    version: 67.7.0
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-prometheus-stack
    valuesFile: values.yaml

configMapGenerator:
  - name: grafana-dashboard-pihole
    files:
      - dashboards/pihole-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-thermal
    files:
      - dashboards/thermal-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"

resources:
  - alerts/temperature-alerts.yaml
  - onzack-cluster-monitoring-recording-rules.yaml
  - onzack-namespace-monitoring-recording-rules.yaml
