# playbooks/yaml/argocd-apps/prometheus/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/kpoxo6op/soyspray.git"
    targetRevision: "kubespray/2.26.0"
    path: playbooks/yaml/argocd-apps/prometheus
    kustomize:
      helm:
        skipCrds: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
