# playbooks/yaml/argocd-apps/prometheus/prometheus-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kpoxo6op/soyspray.git'
    targetRevision: work
    path: playbooks/yaml/argocd-apps/prometheus
    helm:
      chart: kube-prometheus-stack
      repoURL: 'https://prometheus-community.github.io/helm-charts'
      targetRevision: 65.5.0
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
