# playbooks/yaml/argocd-apps/prometheus/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  source:
    repoURL: 'https://github.com/kpoxo6op/soyspray.git'
    targetRevision: work
    path: playbooks/yaml/argocd-apps/prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
