# playbooks/yaml/argocd-apps/prometheus/prometheus-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kpoxo6op/soyspray.git'  # Your Git repository
    targetRevision: work
    path: playbooks/yaml/argocd-apps/prometheus           # Path to your application directory
    helm:
      chart: kube-prometheus-stack                       # Helm chart name
      repoURL: 'https://prometheus-community.github.io/helm-charts'  # Helm chart repository
      targetRevision: 65.5.0                             # Helm chart version
      valueFiles:
        - values.yaml                                    # Reference to your local values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
