apiVersion: v1
kind: Namespace
metadata:
  name: platform-identity
  labels:
    banklab.konghq.com/managed-by: gitops
    banklab.konghq.com/platform-layer: prereq
    banklab.konghq.com/environment: lab
    banklab.konghq.com/data-classification: synthetic
    banklab.konghq.com/owner: platform-identity-team

