apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: obsidian

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap-couchdb.yaml
  - deployment.yaml
  - networkpolicy-couchdb.yaml
  - service-couchdb-headless.yaml
  - service-couchdb.yaml
  - ingress.yaml
