# playbooks/yaml/argocd-apps/plex/initial-config-configmap.yaml
# Switch ManualPortMappingPort from 32400 to 443 so plex.tv advertises the HTTPS-friendly port.
apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-initial-config
  namespace: media
  labels:
    app: plex
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  Preferences.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <Preferences
      AcceptedEULA="1"
      FirstRun="0"
      FriendlyName="Plex"
      enableLocalSecurity="0"
      allowedNetworks="192.168.1.0/255.255.255.0,10.0.0.0/255.0.0.0,172.16.0.0/255.240.0.0"
      DlnaEnabled="0"
      GdmEnabled="0"
      FSEventLibraryUpdatesEnabled="1"
      ScheduledLibraryUpdatesEnabled="0"
      ManualPortMappingMode="1"
      ManualPortMappingPort="443"
      secureConnections="1"
      sendCrashReports="0"
      PublishServerOnPlexOnlineKey="1"
      RelayEnabled="0"
    />
