# playbooks/yaml/argocd-apps/plex/service.yaml
# Service for Plex
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
spec:
  selector:
    app: plex
  ports:
    - name: http
      port: 32400
      targetPort: 32400
      protocol: TCP
  type: ClusterIP
