# playbooks/yaml/argocd-apps/qbittorrent/configmap.yaml
# Seeds qBittorrent WebUI credentials (admin / 123) via PBKDF2 hash.
# Optimized for media stack integrations with Sonarr/LazyLibrarian.
#------------------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-conf
  namespace: media
data:
  qBittorrent.conf: |-
    [AutoRun]
    enabled=false
    program=

    [BitTorrent]
    Session\AddTorrentStopped=true
    Session\AnnounceIP=210.54.32.219
    Session\AnnounceToAllTrackers=true
    Session\ReannounceWhenAddressChanged=true
    Session\AddTorrentStopped=false
    Session\DefaultSavePath=/downloads
    Session\Port=49160
    Session\QueueingSystemEnabled=true
    Session\SSL\Port=9007
    Session\ShareLimitAction=Stop
    Session\SubcategoriesEnabled=true
    Session\TempPath=/downloads/incomplete
    Session\TempPathEnabled=true
    Session\UseCategoryPathsInManualMode=true

    [Categories]
    audiobooks\SavePath=/downloads/audiobooks
    books\SavePath=/downloads/books
    movies\SavePath=/downloads/movies
    scenes\SavePath=/downloads/scenes
    tv\SavePath=/downloads/tv

    [Core]
    AutoDeleteAddedTorrentFile=Never

    [LegalNotice]
    Accepted=true

    [Meta]
    MigrationVersion=8

    [Network]
    PortForwardingEnabled=false
    Proxy\HostnameLookupEnabled=false
    Proxy\Profiles\BitTorrent=true
    Proxy\Profiles\Misc=true
    Proxy\Profiles\RSS=true

    [Preferences]
    Connection\PortRangeMin=49160
    Connection\UPnP=false
    Downloads\SavePath=/downloads
    Downloads\TempPath=/downloads/incomplete
    Downloads\TempPathEnabled=true
    Downloads\TorrentManagementMode=2
    WebUI\Address=*
    WebUI\ServerDomains=*
    WebUI\Username=admin
    WebUI\Password_PBKDF2="@ByteArray(6GuqwbIxFz5yNRLYBYPQIQ==:WyiZHyQ5Hgwnc71PuKmt1NKVAUD9tstuLBcJrP82SkQfalql8giGHqbOc7lly/xbqXEKuvcvrc3Dbg62PNPZBA==)"

