apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-rwx
  namespace: media
  labels:
    app: media-stack
    purpose: shared-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-rwx
  resources:
    requests:
      storage: 100GB
