apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streamlink
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  source:
    repoURL: "https://github.com/kpoxo6op/soyspray.git"
    targetRevision: "HEAD"
    path: playbooks/yaml/argocd-apps/streamlink
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
