apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - namespace.yaml
  - certificate.yaml
  - relay-config.yaml
  - relay-deployment.yaml
  - service.yaml
  - authentik-forward-auth.yaml
  - ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/instance: ai
