apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: boys
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - cloudflared-deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - cloudflared-calico-networkpolicy.yaml
  - cloudflared-host-boundary.yaml
transformers:
  - cluster-scope-transformer.yaml
labels:
  - pairs:
      app.kubernetes.io/instance: boys
