apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: obsidian

resources:
  - configmap-couchdb.yaml
  - deployment-couchdb-rescue.yaml
  - networkpolicy-couchdb.yaml
  - service-couchdb-headless.yaml
  - service-couchdb.yaml
  - ingress.yaml
