apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-livesync-couchdb-rescue-longhorn
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
