# playbooks/argocd/apps/redis/values.yaml
architecture: standalone

auth:
  enabled: false
  sentinel: false

image:
  registry: docker.io
  repository: bitnamilegacy/redis
  tag: 8.2.1-debian-12-r0

primary:
  persistence:
    enabled: true
    storageClass: longhorn
    size: 5Gi
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 200m
  extraEnvVars:
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"

volumePermissions:
  enabled: true
