apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: autism-traits-cloudflared-boundary
  labels:
    app.kubernetes.io/name: autism-traits-cloudflared
    app.kubernetes.io/part-of: autism-traits
spec:
  order: 10
  selector: autism-traits-component == 'cloudflared'
  types:
    - Egress
  egress:
    - action: Allow
      protocol: UDP
      destination:
        nets:
          - 169.254.25.10/32
        ports:
          - 53
    - action: Allow
      protocol: TCP
      destination:
        nets:
          - 169.254.25.10/32
        ports:
          - 53
    - action: Allow
      protocol: TCP
      destination:
        selector: autism-traits-component == 'web'
        ports:
          - 8443
    - action: Allow
      protocol: TCP
      destination:
        nets: &cloudflare-tunnel-endpoints
          - 198.41.192.7/32
          - 198.41.192.27/32
          - 198.41.192.37/32
          - 198.41.192.47/32
          - 198.41.192.57/32
          - 198.41.192.67/32
          - 198.41.192.77/32
          - 198.41.192.107/32
          - 198.41.192.167/32
          - 198.41.192.227/32
          - 198.41.200.13/32
          - 198.41.200.23/32
          - 198.41.200.33/32
          - 198.41.200.43/32
          - 198.41.200.53/32
          - 198.41.200.63/32
          - 198.41.200.73/32
          - 198.41.200.113/32
          - 198.41.200.193/32
          - 198.41.200.233/32
        ports:
          - 7844
    - action: Allow
      protocol: UDP
      destination:
        nets: *cloudflare-tunnel-endpoints
        ports:
          - 7844
    - action: Deny
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: autism-traits-web-zero-egress
  labels:
    app.kubernetes.io/name: autism-traits
    app.kubernetes.io/part-of: autism-traits
spec:
  order: 10
  selector: autism-traits-component == 'web'
  types:
    - Egress
  egress:
    - action: Deny
