apiVersion: builtin
kind: PatchTransformer
metadata:
  name: autism-traits-cluster-scope
patch: |-
  - op: remove
    path: /metadata/namespace
target:
  group: crd.projectcalico.org
  labelSelector: autism-traits-cluster-boundary=true
