apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autism-traits
  labels:
    app.kubernetes.io/name: autism-traits
    app.kubernetes.io/part-of: autism-traits
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - autism.soyspray.vip
      secretName: autism-traits-tls
  rules:
    - host: autism.soyspray.vip
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: autism-traits
                port:
                  name: http
