apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: autism-traits
  labels:
    app.kubernetes.io/name: autism-traits
    app.kubernetes.io/part-of: autism-traits
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: autism-traits
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
  egress: []
