apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-db-active
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgresql
  sources:
    - repoURL: "https://github.com/kpoxo6op/soyspray.git"
      targetRevision: "immich-db-recovery-4"
      path: playbooks/yaml/argocd-apps/cnpg/immich-db-active
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
