apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-tailscale
  namespace: ingress-nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "*.soyspray.vip"
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: ingress-nginx-controller
      port:
        number: 80
