apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-tailscale
  namespace: ingress-nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "podinfo.test.soyspray.vip"
    external-dns.alpha.kubernetes.io/target: "100.69.17.31"
    external-dns.alpha.kubernetes.io/ttl: "60"
    external-dns.alpha.kubernetes.io/set-identifier: "tailscale"
spec:
  ingressClassName: nginx
  rules:
  - host: podinfo.test.soyspray.vip
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ingress-nginx-controller
            port:
              number: 80
