apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.78.3
      helm:
        valueFiles:
          - $values/playbooks/yaml/argocd-apps/tailscale/values.yaml
    - repoURL: https://github.com/kpoxo6op/soyspray.git
      targetRevision: feature/tailscale-vpn
      path: playbooks/yaml/argocd-apps/tailscale
      ref: values-config
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
