apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db-a
  namespace: postgresql
spec:
  bootstrap:
    recovery:
      recoveryTarget:
        targetTime: "2025-10-24 08:35:00+00:00"
