apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-config
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: prometheus
    soyspray.vip/owner: platform
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  project: prometheus-config
  source:
    repoURL: "https://github.com/kpoxo6op/soyspray.git"
    targetRevision: main
    path: apps/prometheus/config
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: "10s"
        factor: 2
        maxDuration: "5m"
