---
bank_argo_finalizers:
  - resources-finalizer.argocd.argoproj.io
  - resources-finalizer.argocd.argoproj.io/background
bank_runtime_applications:
  - banklab-kong
  - banklab-kong-gateway-api
  - banklab-kong-smoke
  - synthetic-bank-apis
  - banklab-kong-security-controls
  - banklab-customer-traffic
  - banklab-kong-operator-dashboard
  - banklab-docs
bank_namespaces:
  - platform-kong
  - platform-kong-smoke
  - synthetic-clients
  - tenant-accounts
  - tenant-cards
  - tenant-customer-profile
  - tenant-fraud
  - tenant-open-banking
  - tenant-payments
  - banklab-docs
bank_kong_crds:
  - ingressclassparameterses.configuration.konghq.com
  - kongclusterplugins.configuration.konghq.com
  - kongconsumergroups.configuration.konghq.com
  - kongconsumers.configuration.konghq.com
  - kongcustomentities.configuration.konghq.com
  - kongingresses.configuration.konghq.com
  - konglicenses.configuration.konghq.com
  - kongplugins.configuration.konghq.com
  - kongupstreampolicies.configuration.konghq.com
  - kongvaults.configuration.konghq.com
  - tcpingresses.configuration.konghq.com
  - udpingresses.configuration.konghq.com
