apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
spec:
  backup:
    target: prefer-standby
  postgresql:
    parameters:
      archive_timeout: 5min
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: immich-offsite
        serverName: immich-db-a-post-ssd-20260506
