apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: banklab-docs
  namespace: banklab-docs
  labels:
    app.kubernetes.io/name: banklab-docs
    app.kubernetes.io/part-of: kong-bank-lab
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: banklab-docs
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - ipBlock:
            cidr: 169.254.25.10/32
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
