# playbooks/yaml/argocd-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  kustomize.buildOptions: --enable-helm
  # test this fix for prometheus ArgoCD sync
  # https://www.reddit.com/r/kubernetes/comments/194wrup/psa_if_you_deploy_kubeprometheusstack_with_argocd/
  application.instanceLabelKey: argocd.argoproj.io/instance
  ui.theme: auto
