apiVersion: loki.grafana.com/v1beta1
kind: LokiStack
metadata:
  name: loki
  namespace: monitoring
spec:
  size: 1x.extra-small
  storage:
    schemas:
      - version: v12
        effectiveDate: "2023-10-15"
    secret:
      name: loki-storage-secret
      type: s3
  template:
    queryFrontend:
      replicas: 1
    ingester:
      replicas: 1
    distributor:
      replicas: 1
    compactor:
      replicas: 1
    gateway:
      replicas: 1

