apiVersion: v1
kind: Secret
metadata:
  name: loki-storage-secret
  namespace: monitoring
type: Opaque
stringData:
  endpoint: "http://object-storage.monitoring.svc.cluster.local:9000"
  bucketnames: "loki"
  access_key_id: "minioadmin"
  access_key_secret: "minioadmin"
  region: "us-east-1"

