apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-operator-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: loki-operator
    targetRevision: "2.12.0"
    helm:
      releaseName: loki-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - AllowClusterResourceInNamespacedApp=true

