apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: cert-manager
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Add external-dns annotations to automatically update DNS
    external-dns.alpha.kubernetes.io/hostname: "test.soyspray.vip"
    external-dns.alpha.kubernetes.io/ttl: "120"
spec:
  # Change to tailscale class
  ingressClassName: tailscale
  tls:
    - hosts:
        - test.soyspray.vip
      secretName: test-tls
  rules:
    - host: test.soyspray.vip
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-web
                port:
                  number: 80
