apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
---
# Adding Tailscale LoadBalancer service
apiVersion: v1
kind: Service
metadata:
  name: test-service-tailscale
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: test.soyspray.vip
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
