apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/network-policy.yaml
configMapGenerator:
  - name: media-helper-code
    files:
      - app.py=app/app.py
      - channels.json=app/channels.json
generatorOptions:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
labels:
  - pairs:
      app.kubernetes.io/name: media-helper
      app.kubernetes.io/part-of: live-tv
    includeSelectors: false
