apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/network-policy.yaml
labels:
- pairs:
    app.kubernetes.io/name: media-helper
    app.kubernetes.io/part-of: live-tv
  includeSelectors: false
