apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: splunk-web
  namespace: splunk
spec:
  secretName: splunk-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - splunk.soyspray.vip
