apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: splunk

configMapGenerator:
  - name: splunk-rest-pipeline
    files:
      - pipeline/bootstrap.py
      - pipeline/splunk_dashboard_pipeline.py
    options:
      disableNameSuffixHash: true
  - name: splunk-rest-dashboards
    files:
      - dashboards/ops-overview.xml
      - dashboards/platform-posture.xml
      - dashboards/rest-pipeline-health.xml
    options:
      disableNameSuffixHash: true

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - bootstrap-job.yaml
