apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: banklab-fraud-decisions
  namespace: tenant-fraud
  annotations:
    konghq.com/plugins: banklab-key-auth,banklab-acl,banklab-rate-limit,banklab-correlation-id
  labels:
    banklab.konghq.com/managed-by: gitops
    banklab.konghq.com/platform-layer: synthetic-api
    banklab.konghq.com/environment: lab
    banklab.konghq.com/data-classification: synthetic
    banklab.konghq.com/lifecycle: sandbox
    banklab.konghq.com/auth-profile: kong-oss-goal004-auth
    banklab.konghq.com/auth-state: authenticated-required
    banklab.konghq.com/authorization-profile: acl-goal004-api-groups
    banklab.konghq.com/rate-limit-profile: goal004-internal-redis-3rps
    banklab.konghq.com/goal: goal-004
    banklab.konghq.com/api-domain: fraud-decisions
    banklab.konghq.com/owner: tenant-fraud-team
    banklab.konghq.com/exposure: internal
spec:
  parentRefs:
  - name: kong-internal
    namespace: platform-kong
    sectionName: http
  hostnames:
  - api.internal.banklab.test
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /fraud/v1
    backendRefs:
    - name: banklab-fraud-decisions-api
      port: 80
