apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap-mock-responses.yaml
- deployment.yaml
- service.yaml
- httproute-internal.yaml
- networkpolicy-allow-kong.yaml
