apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: critical-recent
  namespace: longhorn-system
spec:
  name: critical-recent
  cron: '*/30 * * * *'
  task: backup-force-create
  groups: [critical]
  retain: 48
  concurrency: 1
  labels:
    soyspray-policy: critical-recent
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: critical-daily
  namespace: longhorn-system
spec:
  name: critical-daily
  cron: '15 14 * * *'
  task: backup-force-create
  groups: [critical]
  retain: 30
  concurrency: 1
  labels:
    soyspray-policy: critical-daily
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: durable-small-daily
  namespace: longhorn-system
spec:
  name: durable-small-daily
  cron: '45 15 * * *'
  task: backup-force-create
  groups: [durable-small]
  retain: 30
  concurrency: 1
  labels:
    soyspray-policy: durable-small-daily
