recovery_claims:
  boys:
    namespace: boys
    claim: boys-data
  vaultwarden:
    namespace: vaultwarden
    claim: vaultwarden-data
  obsidian:
    namespace: obsidian
    claim: obsidian-livesync-couchdb-rescue-longhorn
  dispatcharr-data:
    namespace: media
    claim: dispatcharr-data
    uid: 1000
  zigbee2mqtt-data:
    namespace: home-automation
    claim: zigbee2mqtt-data
  booklore-data:
    namespace: media
    claim: booklore-data
    uid: 1000
  home-assistant-config:
    namespace: home-automation
    claim: home-assistant-config
  booklore-config:
    namespace: media
    claim: booklore-config
    uid: 1000
  qbittorrent-config:
    namespace: media
    claim: qbittorrent-config
    uid: 1000
  booklore-mariadb:
    namespace: media
    claim: booklore-mariadb
    uid: 1000
  mosquitto-data:
    namespace: home-automation
    claim: mosquitto-data
    uid: 1883
  jellyfin-config-v2:
    namespace: media
    claim: jellyfin-config-v2
  redis-data-redis-master-0:
    namespace: redis
    claim: redis-data-redis-master-0
    uid: 1001
  lazylibrarian-books:
    namespace: media
    claim: lazylibrarian-books
    uid: 1000
  lazylibrarian-config:
    namespace: media
    claim: lazylibrarian-config
    uid: 1000
