# apps/booklore/manifests/booklore-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: booklore
  namespace: argocd
  labels:
    soyspray.vip/owner: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  project: legacy-workloads
  source:
    repoURL: "https://github.com/kpoxo6op/soyspray.git"
    targetRevision: main
    path: apps/booklore/manifests
  destination:
    server: "https://kubernetes.default.svc"
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
