apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voice-assistant
  namespace: argocd
  labels:
    soyspray.vip/owner: household
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  project: legacy-workloads
  source:
    repoURL: https://github.com/kpoxo6op/soyspray.git
    targetRevision: main
    path: apps/voice-assistant/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: home-automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 0
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
