apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana-alloy
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: observability
  annotations:
    description: Grafana Alloy Flow configuration for Kubernetes pod logs and events.
data:
  config.alloy: |
    logging {
      level = "info"
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    loki.source.kubernetes "pods" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [loki.process.pod_logs.receiver]
    }

    loki.process "pod_logs" {
      forward_to = [loki.write.default.receiver]

      stage.cri {}

      stage.multiline {
        firstline     = "^\\d{4}-\\d{2}-\\d{2}|^[A-Z]\\d{4}|^\\[|^\\{|^time="
        max_wait_time = "3s"
      }

      stage.label_drop {
        values = ["filename"]
      }

      stage.static_labels {
        values = { job = "kubernetes-pods", cluster = "soyspray" }
      }
    }

    loki.write "default" {
      endpoint {
        url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
      }
    }
