apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-events-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana-alloy
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: observability
data:
  config.alloy: |
    logging {
      level = "info"
    }

    loki.source.kubernetes_events "events" {
      job_name   = "kubernetes-events"
      forward_to = [loki.process.events.receiver]
    }

    loki.process "events" {
      stage.logfmt {
        mapping = {
          reason               = "reason",
          involved_object_kind = "involved_object_kind",
          involved_object_name = "involved_object_name",
          reporting_controller = "reporting_controller",
          type                 = "type",
        }
      }

      stage.labels {
        values = {
          kubernetes_event_reason               = "reason",
          kubernetes_event_involved_object_kind = "involved_object_kind",
          kubernetes_event_involved_object_name = "involved_object_name",
          kubernetes_event_reporting_controller = "reporting_controller",
          type                                  = "type",
        }
      }

      stage.static_labels {
        values = { cluster = "soyspray" }
      }

      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
      }
    }

