apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: alloy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana-alloy
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-alloy
  namespaceSelector:
    matchNames:
      - monitoring
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s

