apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana-alloy
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-alloy
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-alloy
        app.kubernetes.io/component: agent
        app.kubernetes.io/part-of: observability
    spec:
      serviceAccountName: alloy
      hostNetwork: false
      dnsPolicy: ClusterFirst
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: alloy
          image: grafana/alloy:v1.11.2
          imagePullPolicy: IfNotPresent
          args:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - --storage.path=/var/lib/alloy/data
            - /etc/alloy/config.alloy
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: http-metrics
              containerPort: 12345
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 75m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: data
              mountPath: /var/lib/alloy/data
            - name: pods
              mountPath: /var/log/pods
              readOnly: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: alloy-config
        - name: data
          hostPath:
            path: /var/lib/alloy/data
            type: DirectoryOrCreate
        - name: pods
          hostPath:
            path: /var/log/pods
