apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana-alloy
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy
  labels:
    app.kubernetes.io/name: grafana-alloy
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: observability
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - pods
      - pods/log
      - namespaces
      - services
      - endpoints
      - events
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy
  labels:
    app.kubernetes.io/name: grafana-alloy
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy
subjects:
  - kind: ServiceAccount
    name: alloy
    namespace: monitoring
