apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: ruler
    app.kubernetes.io/part-of: observability
    loki.grafana.com/rule: "1"
data:
  kubernetes-critical.yaml: |
    groups:
      - name: kubernetes-critical
        rules:
          - alert: KubernetesPodCrashLoopingLogs
            expr: |
              sum by (namespace, pod) (
                label_replace(
                  count_over_time({cluster="soyspray", job="kubernetes-events"} |= "Back-off restarting failed container"[5m]),
                  "pod", "$1", "kubernetes_event_involved_object_name", "(.*)"
                )
              ) > 0
            for: 10m
            labels:
              severity: critical
            annotations:
              summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping"
              description: |
                Loki detected repeated CrashLoopBackOff events for pod {{ $labels.namespace }}/{{ $labels.pod }} in the last 10 minutes.

  application-errors.yaml: |
    groups:
      - name: application-errors
        rules:
          - alert: ApplicationErrorBurst
            expr: |
              sum by (namespace, pod) (
                count_over_time({cluster="soyspray", job="kubernetes-pods"} |~ "(?i)\\b(error|fatal)\\b" [5m])
              ) > 50
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Error burst in {{ $labels.namespace }}/{{ $labels.pod }}"
              description: |
                More than 50 log lines containing 'error' or 'fatal' were observed in 5m for pod {{ $labels.namespace }}/{{ $labels.pod }}. Investigate recent deployments, crashes, or upstream dependencies.

  storage-mount-failures.yaml: |
    groups:
      - name: storage-mount-failures
        rules:
          - alert: VolumeMountAttachFailures
            expr: |
              sum by (namespace, pod) (
                label_replace(
                  count_over_time(
                    {cluster="soyspray", job="kubernetes-events", type="Warning"}
                    |~ "(?i)FailedMount|FailedAttachVolume|VolumeAttachmentFailed|Unable to attach or mount volumes|MountVolume\\.SetUp failed"
                    [10m]
                  ),
                  "pod", "$1", "kubernetes_event_involved_object_name", "(.*)"
                )
              ) > 0
            for: 10m
            labels:
              severity: critical
            annotations:
              summary: "Volume attach/mount failure for {{ $labels.namespace }}/{{ $labels.pod }}"
              description: |
                Kubernetes reported volume attach/mount warnings (FailedMount/FailedAttachVolume) for {{ $labels.namespace }}/{{ $labels.pod }} within the last 10 minutes. Check Longhorn volume status, node health, and kubelet logs.

  immich-backup.yaml: |
    groups:
      - name: immich-backup
        rules:
          - alert: ImmichMediaBackupFailureImmediate
            expr: |
              sum by (namespace) (
                count_over_time({namespace="immich", container="aws-sync"}
                  |~ "(?i)(an error occurred \\(|error|accessdenied|expiredtoken|slowdown|requesttimetoo skewed|read-only file system|connection reset)" [5m])
              ) > 0
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "Immich media offsite sync failed (aws-cli errors)"
              description: "aws-cli in immich-media-offsite-sync is emitting errors in the last 5m."

  immich-backup-events.yaml: |
    groups:
      - name: immich-backup-events
        rules:
          - alert: ImmichMediaBackupBackoffLimitExceeded
            expr: |
              count_over_time({cluster="soyspray", job="kubernetes-events"} |= "BackoffLimitExceeded" |= "immich-media-offsite-sync" [5m]) > 0
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "immich-media-offsite-sync backoff limit exceeded"
              description: "Kubernetes reports BackoffLimitExceeded for immich-media-offsite-sync."

  cnpg-backup.yaml: |
    groups:
      - name: cnpg-backup
        rules:
          - alert: CNPGBackupBarmanError
            expr: |
              sum by (namespace) (
                count_over_time({namespace="postgresql"} |= "barman"
                  |~ "(?i)(error|failed|fatal)" [5m])
              ) > 0
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "CNPG barman backup error"
              description: "CNPG cluster logs contain barman ERROR/failed in the last 5m."

          - alert: CNPGWalArchiveFailure
            expr: |
              sum by (namespace) (
                count_over_time({namespace="postgresql"}
                  |~ "(?i)archive_command.*(failed|returned)" [5m])
              ) > 0
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "PostgreSQL WAL archiving failing (archive_command)"
              description: "postgres reports archive_command failure in the last 5m."

  backup-error-burst.yaml: |
    groups:
      - name: backup-error-burst
        rules:
          - alert: BackupErrorBurst
            expr: |
              sum by (namespace) (
                rate(({namespace=~"immich|postgresql"} |~ "(?i)(error|failed|fatal)")[5m])
              ) > 0.5
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Backup error burst"
              description: "Sustained error rate detected across backup logs."
