apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/kpoxo6op/soyspray.git"
    targetRevision: "HEAD"
    path: playbooks/yaml/argocd-apps/alloy-loki-manual
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      retry:
        limit: 5
        backoff:
          duration: "10s"
          factor: 2
          maxDuration: "5m"
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
