apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: observability
  annotations:
    description: Loki configuration for single-binary deployment with retention and ruler enabled.
data:
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    common:
      instance_addr: 127.0.0.1
      path_prefix: /var/loki
      ring:
        kvstore:
          store: inmemory
      replication_factor: 1

    storage_config:
      filesystem:
        directory: /var/loki/chunks

    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      retention_period: 14d
      max_cache_freshness_per_query: 10m
      allow_structured_metadata: false
      max_query_lookback: 14d

    compactor:
      working_directory: /var/loki/compactor
      retention_enabled: true
      delete_request_store: filesystem
      compactor_ring:
        kvstore:
          store: inmemory

    ruler:
      alertmanager_url: http://alertmanager-operated.monitoring.svc:9093
      rule_path: /var/loki/rules-temp
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      ring:
        kvstore:
          store: inmemory
