# playbooks/yaml/argocd-apps/pihole-exporter/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-exporter
  namespace: pihole
  labels:
    app: pihole-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole-exporter
  template:
    metadata:
      labels:
        app: pihole-exporter
    spec:
      containers:
        - name: pihole-exporter
          image: ekofr/pihole-exporter:v0.4.0
          ports:
            - containerPort: 9617
          env:
            - name: PIHOLE_HOSTNAME
              value: "pihole-web.pihole.svc.cluster.local"
            - name: PIHOLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: PIHOLE_PASSWORD
            - name: PORT
              value: "9617"
            - name: INTERVAL
              value: "10s"
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9617
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9617
            initialDelaySeconds: 10
            periodSeconds: 20
