# playbooks/yaml/argocd-apps/pihole-exporter/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pihole-exporter
  namespace: pihole
  labels:
    app: pihole-exporter
spec:
  ports:
    - protocol: TCP
      port: 9617
      targetPort: 9617
  selector:
    app: pihole-exporter
  type: ClusterIP
