# playbooks/yaml/argocd-apps/pihole-exporter/values.yaml
service:
  port: 9617

extraEnvVars:
  INTERVAL: "10s"
  PIHOLE_HOSTNAME: "pihole-web.pihole.svc.cluster.local"
  PORT: "80"

secret:
  generate: true
  secretEnvVars:
    PIHOLE_PASSWORD: "admin"

serviceMonitor:
  enable: true
