apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: postgresql
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.3.0
  storage:
    size: 20Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-app-secret
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - ALTER DATABASE immich SET search_path TO "$user", public, vectors;
        - ALTER SCHEMA vectors OWNER TO immich;
        - GRANT SELECT ON TABLE pg_vector_index_stat TO immich;
  postgresql:
    shared_preload_libraries:
    - vectors
