# playbooks/yaml/argocd-apps/readarr/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
  namespace: media
  labels:
    app: readarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: readarr
  template:
    metadata:
      labels:
        app: readarr
        component: main
    spec:
      initContainers:
        - name: seed-config
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              if [ ! -f /config/config.xml ]; then
                cp /template/config.xml /config/config.xml
              fi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config-template
              mountPath: /template
        - name: setup-books-library
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "=== Setting up BooksLibrary folder ==="
              mkdir -p /downloads/BooksLibrary
              chown -R 1000:1000 /downloads/BooksLibrary
              chmod -R u+rw /downloads/BooksLibrary
              ls -la /downloads/
              echo "=== BooksLibrary setup complete ==="
          volumeMounts:
            - name: downloads
              mountPath: /downloads
      containers:
      - name: readarr
        image: linuxserver/readarr:0.4.14-develop
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8787
          name: http
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Pacific/Auckland"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: readarr-config
      - name: downloads
        persistentVolumeClaim:
          claimName: qbittorrent-downloads
      - name: config-template
        configMap:
          name: readarr-initial-config
