apiVersion: v1
kind: ConfigMap
metadata:
  name: readarr-initial-config
  namespace: media
data:
  config.xml: |-
    <Config>
      <BindAddress>*</BindAddress>
      <Port>8787</Port>
      <SslPort>6868</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>True</LaunchBrowser>
      <ApiKey>a85bb8f2ab19425f9c8c0bbc6f0aa29c</ApiKey>
      <AuthenticationMethod>External</AuthenticationMethod>
      <AuthenticationRequired>Enabled</AuthenticationRequired>
      <Branch>develop</Branch>
      <LogLevel>debug</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase></UrlBase>
      <InstanceName>Readarr</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
    </Config>
