apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc-config.yaml
  - service.yaml
  - ingress.yaml
  - deployment.yaml
  - initial-config-configmap.yaml
  - bootstrap-scripts-cm.yaml
  - bootstrap-job.yaml

configMapGenerator:
  - name: readarr-payloads
    namespace: media
    files:
      - qbittorrent.json=qbittorrent_payload.json
      - rootfolder.json=rootfolder_payload.json
    options:
      disableNameSuffixHash: true
