apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: readarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kpoxo6op/soyspray.git
    targetRevision: "housekeeping"
    path: playbooks/yaml/argocd-apps/readarr
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
