apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: "2026.5.6"
      helm:
        releaseName: authentik
        valueFiles:
          - $values/playbooks/argocd/applications/security/authentik/values.yaml
        parameters:
          - name: 'server.podAnnotations.soyspray\.vip/runtime-secret-resource-version'
            value: "AUTHENTIK_RUNTIME_SECRET_RESOURCE_VERSION"
          - name: 'worker.podAnnotations.soyspray\.vip/runtime-secret-resource-version'
            value: "AUTHENTIK_RUNTIME_SECRET_RESOURCE_VERSION"
    - repoURL: https://github.com/kpoxo6op/soyspray.git
      targetRevision: "HEAD"
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
