# playbooks/argocd/applications/media/booklore/booklore-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: booklore-db-secret
  namespace: media
type: Opaque
stringData:
  db-password: CHANGE_ME_WITH_NON_REPO_SECRET
  db-user: booklore
  db-name: booklore
