apiVersion: v1
kind: Service
metadata:
  name: banklab-customer-profile-api
  namespace: tenant-customer-profile
  labels:
    banklab.konghq.com/managed-by: gitops
    banklab.konghq.com/platform-layer: synthetic-api
    banklab.konghq.com/api-domain: customer-profile
    banklab.konghq.com/owner: tenant-customer-profile-team
    banklab.konghq.com/exposure: internal
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: banklab-customer-profile-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
