apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - bootstrap.yaml
  - deployments.yaml
  - services.yaml
  - storage.yaml
  - network-policies.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: home-assistant-voice
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
