apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: temperature-alerts
  labels:
    release: prometheus
spec:
  groups:
    - name: temperature
      rules:
        - alert: HighTemperatureWarning
          expr: node_thermal_zone_temp > 70
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High temperature on {{ $labels.instance }}"
            description: "Temperature above 70째C on {{ $labels.instance }}"
            value: "{{ $value }}째C"

        - alert: HighTemperatureCritical
          expr: node_thermal_zone_temp > 80
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Critical temperature on {{ $labels.instance }}"
            description: "Temperature above 80째C on {{ $labels.instance }}"
            value: "{{ $value }}째C"
