apiVersion: apps/v1
kind: Deployment
metadata:
  name: banklab-payments-api
  namespace: tenant-payments
  labels:
    banklab.konghq.com/managed-by: gitops
    banklab.konghq.com/platform-layer: synthetic-api
    banklab.konghq.com/environment: lab
    banklab.konghq.com/data-classification: synthetic
    banklab.konghq.com/lifecycle: sandbox
    banklab.konghq.com/auth-profile: none-temporary-goal003-sandbox
    banklab.konghq.com/auth-state: temporary-no-auth
    banklab.konghq.com/goal: goal-003
    banklab.konghq.com/api-domain: payments
    banklab.konghq.com/owner: tenant-payments-team
    banklab.konghq.com/exposure: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: banklab-payments-api
  template:
    metadata:
      labels:
        banklab.konghq.com/managed-by: gitops
        banklab.konghq.com/platform-layer: synthetic-api
        banklab.konghq.com/environment: lab
        banklab.konghq.com/data-classification: synthetic
        banklab.konghq.com/lifecycle: sandbox
        banklab.konghq.com/auth-profile: none-temporary-goal003-sandbox
        banklab.konghq.com/auth-state: temporary-no-auth
        banklab.konghq.com/goal: goal-003
        banklab.konghq.com/api-domain: payments
        banklab.konghq.com/owner: tenant-payments-team
        banklab.konghq.com/exposure: internal
        app.kubernetes.io/name: banklab-payments-api
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.27-alpine
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: mock-responses
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        - name: tmp
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: mock-responses
        configMap:
          name: banklab-payments-mock-responses
      - name: tmp
        emptyDir: {}
