# playbooks/infra_configs/argocd-apps/pihole/pihole-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MoJo2600/pihole-kubernetes
    path: charts/pihole
    targetRevision: pihole-2.26.1
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
