# playbooks/infra_configs/argocd-apps/pihole/pihole-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://mojo2600.github.io/pihole-kubernetes'  # External Helm chart repo
    targetRevision: 2.26.1   # Chart version from external repo
    chart: pihole            # Helm chart name
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/kpoxo6op/soyspray/work/playbooks/infra_configs/argocd-apps/pihole/values.yaml  # URL to your custom values.yaml in your GitHub repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
