webHttp: "80"
webHttps: "443"

replicaCount: 1
strategyType: RollingUpdate
hostNetwork: false
hostname: ""
virtualHost: "pi.hole"
privileged: false

persistentVolumeClaim:
  enabled: true
  storageClass: local-storage
  size: 500Mi
  accessModes:
    - ReadWriteOnce

serviceWeb:
  loadBalancerIP: 192.168.1.122
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
  http:
    enabled: true
    port: 80
  https:
    enabled: false
    port: 443

serviceDns:
  mixedService: true
  loadBalancerIP: 192.168.1.122
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
  port: 53

serviceDhcp:
  enabled: false
  type: ClusterIP
  port: 67
  externalTrafficPolicy: Cluster

dualStack:
  enabled: false

doh:
  enabled: false

monitoring:
  sidecar:
    enabled: false
    image:
      repository: prom/prometheus
      tag: latest
      pullPolicy: IfNotPresent
    port: 9100
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  podMonitor:
    enabled: false
    namespace: ""
    interval: 30s
    bearerTokenFile: ""
    bearerTokenSecret:
      name: ""
      key: ""

ingress:
  enabled: false
  hosts: []
  path: /
  annotations: {}
  tls: []
  ingressClassName: ""

podDisruptionBudget:
  enabled: false

antiaff:
  enabled: false

podDnsConfig:
  enabled: false

dnsmasq:
  staticDhcpEntries: []
  upstreamServers: []
  customDnsEntries: []
  customSettings: []
  additionalHostsEntries: []
  customCnameEntries: []

admin:
  enabled: true
  existingSecret: ""
  passwordKey: "password"
  adminPassword: "adminpassword"

dnsHostPort:
  enabled: false
  port: 53

image:
  repository: pihole/pihole
  tag: latest
  pullPolicy: IfNotPresent

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
