apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: vaultwarden
spec:
  project: vaultwarden
  source:
    repoURL: https://github.com/kpoxo6op/soyspray.git
    targetRevision: HEAD
    path: kubernetes/vaultwarden
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/part-of: vaultwarden
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/enforce-version: v1.35
        pod-security.kubernetes.io/warn: restricted
        pod-security.kubernetes.io/warn-version: v1.35
