apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../apps/headlamp/argocd
  - ../apps/autism-traits/argocd
  - ../apps/boys/argocd
  - ../apps/external-dns/argocd
  - ../apps/domain-health/argocd
  - ../apps/vaultwarden/argocd
  - ../apps/obsidian-livesync/argocd
