# playbooks/argocd/apps/threadfin/deployment.yaml
# Deployment for Threadfin using fyb3roptik/threadfin:1.2.37
apiVersion: apps/v1
kind: Deployment
metadata:
  name: threadfin
  namespace: media
  labels:
    app: threadfin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: threadfin
  template:
    metadata:
      labels:
        app: threadfin
        component: main
    spec:
      # Init container to bootstrap configuration from ConfigMaps
      initContainers:
        - name: bootstrap-config
          image: busybox:stable
          command: ["/bin/sh", "-c"]
          args:
            - >
              set -e;
              echo "Bootstrapping Threadfin configuration...";
              mkdir -p /config /config/backup;
              [ -s /config/settings.json ] || cp /bootstrap-config/settings.json /config/settings.json;
              [ -s /config/urls.json ] || cp /bootstrap-config/urls.json /config/urls.json;
              echo "Configuration bootstrap complete";
              ls -la /config/
          volumeMounts:
            - name: bootstrap-config
              mountPath: /bootstrap-config
              readOnly: true
            - name: config
              mountPath: /config

      containers:
        - name: threadfin
          image: fyb3roptik/threadfin:1.2.37
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 34400
              name: http
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: THREADFIN_BRANCH
              value: "main"
            - name: THREADFIN_PORT
              value: "34400"
            - name: THREADFIN_DEBUG
              value: "0"
            - name: TZ
              value: "Pacific/Auckland"
          volumeMounts:
            - name: config
              mountPath: /home/threadfin/conf
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: threadfin-config
        # ConfigMap volumes for bootstrap
        - name: bootstrap-config
          configMap:
            name: threadfin-bootstrap-config
