apiVersion: v1
kind: Namespace
metadata:
  name: assembly-guide
  labels:
    app.kubernetes.io/part-of: assembly-guide
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.35
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.35
