---
- name: Deploy the autism traits site
  ansible.builtin.import_tasks: enabled.yml
  when: autism_traits_enabled | bool
  tags: autism_traits

- name: Remove the autism traits site
  ansible.builtin.import_tasks: disabled.yml
  when: not (autism_traits_enabled | bool)
  tags: autism_traits
