apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads-local-node-0
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: 1800Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-media
  local:
    path: /srv/media/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node-0
