# playbooks/argocd/apps/pihole-exporter/pihole-exporter-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kpoxo6op/soyspray.git
    targetRevision: "main"
    path: playbooks/argocd/apps/pihole-exporter
    kustomize:
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
