apiVersion: v1
kind: Secret
metadata:
  name: loki-object-storage
  namespace: monitoring
type: Opaque
stringData:
  bucketnames: loki
  endpoint: http://object-storage.monitoring.svc.cluster.local:9000
  access_key_id: minioadmin
  access_key_secret: minioadmin
  region: us-east-1

