---
voice_assistant_enabled: true
voice_assistant_target_revision: HEAD
voice_assistant_ha_token: >-
  {{ lookup('ansible.builtin.env', 'VOICE_ASSISTANT_HA_TOKEN') | default('', true) }}
voice_assistant_gi_model_path: >-
  {{ lookup('ansible.builtin.env', 'VOICE_ASSISTANT_GI_MODEL_PATH') | default('', true) }}
voice_assistant_gi_model_configmap_name: openwakeword-gi-model-v7b
voice_assistant_gi_model_sha256: e61dd9f2880f226b05b8f9885c053fa7ec7805170c3f3b4d56427c6294cb4be0
voice_assistant_gi_model_retired_configmaps: []
