apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-alloy
  labels:
    app.kubernetes.io/name: grafana-alloy
    app.kubernetes.io/part-of: soyspray-observability
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - namespaces
      - nodes
      - services
      - endpoints
      - events
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
