apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana-alloy-logs
  namespace: logging
  labels:
    app.kubernetes.io/name: grafana-alloy
    app.kubernetes.io/component: logs
    app.kubernetes.io/part-of: soyspray-observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-alloy
      app.kubernetes.io/component: logs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-alloy
        app.kubernetes.io/component: logs
        app.kubernetes.io/part-of: soyspray-observability
    spec:
      serviceAccountName: grafana-alloy
      hostPID: false
      hostNetwork: false
      tolerations:
        - operator: Exists
      containers:
        - name: grafana-alloy
          image: grafana/alloy:1.3.1
          imagePullPolicy: IfNotPresent
          args:
            - "run"
            - "/etc/alloy/config.alloy"
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdocker
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlibcontainerd
              mountPath: /var/lib/containerd
              readOnly: true
            - name: machineid
              mountPath: /etc/machine-id
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: grafana-alloy-logs
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdocker
          hostPath:
            path: /var/lib/docker/containers
            type: DirectoryOrCreate
        - name: varlibcontainerd
          hostPath:
            path: /var/lib/containerd
            type: DirectoryOrCreate
        - name: machineid
          hostPath:
            path: /etc/machine-id
            type: File
