apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-alloy-events
  namespace: logging
  labels:
    app.kubernetes.io/name: grafana-alloy
    app.kubernetes.io/component: events
    app.kubernetes.io/part-of: soyspray-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-alloy
      app.kubernetes.io/component: events
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-alloy
        app.kubernetes.io/component: events
        app.kubernetes.io/part-of: soyspray-observability
    spec:
      serviceAccountName: grafana-alloy
      containers:
        - name: grafana-alloy
          image: grafana/alloy:1.3.1
          imagePullPolicy: IfNotPresent
          args:
            - "run"
            - "/etc/alloy/config.alloy"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
      volumes:
        - name: config
          configMap:
            name: grafana-alloy-events
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: grafana-alloy
                    app.kubernetes.io/component: logs
