apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banklab-kong-smoke
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: kong-bank-lab
spec:
  project: banklab-kong
  source:
    repoURL: https://github.com/kpoxo6op/soyspray.git
    targetRevision: HEAD
    path: platform/kong/smoke
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-kong-smoke
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions:
      - CreateNamespace=true
