# playbooks/yaml/argocd-apps/sonarr/deployment.yaml
# Deployment for Sonarr using linuxserver/sonarr:4.0.15
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
  labels:
    app: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
        component: main
    spec:
      initContainers:
        - name: init-config
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              if [ ! -f /config/config.xml ]; then
                echo "Seeding initial Sonarr configuration..."
                cp /initial-config/config.xml /config/config.xml
                chown 1000:1000 /config/config.xml
              else
                echo "Sonarr configuration already exists, skipping seed."
              fi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: initial-config
              mountPath: /initial-config
      containers:
        - name: sonarr
          image: linuxserver/sonarr:4.0.15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8989
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Pacific/Auckland"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tv
              mountPath: /tv
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: tv
          hostPath:
            path: /media/tv
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /media/downloads
            type: DirectoryOrCreate
        - name: initial-config
          configMap:
            name: sonarr-initial-config
