apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-initial-config
  namespace: media
  labels:
    app: sonarr
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  config.xml: |-
    <Config>
      <BindAddress>*</BindAddress>
      <Port>8989</Port>
      <SslPort>9898</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>False</LaunchBrowser>
      <ApiKey>a85bb8f2ab19425f9c8c0bbc6f0aa29c</ApiKey>
      <AuthenticationMethod>External</AuthenticationMethod>
      <AuthenticationRequired>Enabled</AuthenticationRequired>
      <Branch>main</Branch>
      <LogLevel>info</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase></UrlBase>
      <InstanceName>Sonarr</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
    </Config>
