# playbooks/yaml/argocd-apps/threadfin/deployment.yaml
# Deployment for Threadfin using fyb3roptik/threadfin:1.2.37
apiVersion: apps/v1
kind: Deployment
metadata:
  name: threadfin
  namespace: media
  labels:
    app: threadfin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: threadfin
  template:
    metadata:
      labels:
        app: threadfin
        component: main
    spec:
      containers:
        - name: threadfin
          image: fyb3roptik/threadfin:1.2.37
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 34400
              name: http
          env:
            - name: THREADFIN_PORT
              value: "34400"
            - name: THREADFIN_DEBUG
              value: "0"
            - name: TZ
              value: "Pacific/Auckland"
          volumeMounts:
            - name: config
              mountPath: /home/threadfin/conf
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: threadfin-config
