# playbooks/yaml/argocd-apps/headlamp/values.yaml
ingress:
  enabled: true
  ingressClassName: nginx
  tls:
    - hosts:
        - headlamp.soyspray.vip
      secretName: prod-cert-tls
  hosts:
    - host: headlamp.soyspray.vip
      paths:
        - path: /
          type: Prefix

config:
  oidc:
    secret:
      create: false
    externalSecret:
      enabled: true
      name: headlamp-oidc

extraManifests:
  - |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: authentik-cluster-admins
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: oidc:cluster-admins
