# playbooks/yaml/argocd-apps/postgresql/kustomization.yaml
# Kustomization uses the official Bitnami 'postgresql' chart.
# We load values from 'values.yaml'. The release name is 'postgresql'.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: postgresql
    repo: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: 16.6.3
    releaseName: postgresql
    valuesFile: values.yaml

namespace: postgresql
