# playbooks/yaml/argocd-apps/postgresql/kustomization.yaml
# Simplified kustomization for PostgreSQL namespace.
# Helm chart is now sourced directly via ArgoCD's multi-source OCI configuration.
# This file maintains namespace and any future Kustomize overlays.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgresql

# Note: helmCharts section removed - chart is now pulled via ArgoCD OCI source
# to resolve Bitnami OCI migration compatibility issues
