# playbooks/yaml/argocd-apps/postgresql/postgresql-application.yaml
# Defines the ArgoCD Application for PostgreSQL using Bitnami OCI Helm chart.
# Uses multi-source configuration: OCI chart + Git values to resolve Bitnami OCI migration issues.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgresql
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: "16.7.27"
      helm:
        valueFiles:
          - $values/playbooks/yaml/argocd-apps/postgresql/values.yaml
    - repoURL: "https://github.com/kpoxo6op/soyspray.git"
      targetRevision: "main"
      path: .
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
