# playbooks/yaml/argocd-apps/postgresql/postgresql-application.yaml
# Defines the ArgoCD Application for PostgreSQL using the Bitnami chart.
# The Helm chart is driven by the 'values.yaml' and 'kustomization.yaml' in this folder.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgresql
  source:
    repoURL: "https://github.com/kpoxo6op/soyspray.git"
    targetRevision: "v1.14.0"
    path: playbooks/yaml/argocd-apps/postgresql
    kustomize:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
