# File: playbooks/infra_configs/argocd-apps/pihole/configmaps/custom-dns-configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-dns-configmap
  namespace: pihole
data:
  custom.list: |
    192.168.1.122 pihole.lan
    192.168.1.121 argocd.lan
