apiVersion: v1
kind: ServiceAccount
metadata:
  name: retail-accounts-api-applier
  namespace: tenant-accounts
  labels:
    platform.soyspray.io/managed-by: gitops
    platform.soyspray.io/goal: goal-005
    platform.soyspray.io/tenant: retail-accounts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-api-applier
  namespace: tenant-payments
  labels:
    platform.soyspray.io/managed-by: gitops
    platform.soyspray.io/goal: goal-005
    platform.soyspray.io/tenant: payments
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: risk-compliance-api-applier
  namespace: tenant-fraud
  labels:
    platform.soyspray.io/managed-by: gitops
    platform.soyspray.io/goal: goal-005
    platform.soyspray.io/tenant: risk-compliance
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong-platform-change-applier
  namespace: platform-kong
  labels:
    platform.soyspray.io/managed-by: gitops
    platform.soyspray.io/goal: goal-005
    platform.soyspray.io/tenant: kong-platform
