apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami/external-dns
      chart: external-dns
      targetRevision: 8.3.10
      helm:
        valueFiles:
          - $values/playbooks/yaml/argocd-apps/external-dns/values.yaml
    - repoURL: https://github.com/kpoxo6op/soyspray.git
      targetRevision: feature/tailscale-vpn
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
