apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- paired-backup.yaml
images:
- name: immich-backup-scripts
  newName: ghcr.io/kpoxo6op/immich-backup-scripts
  digest: sha256:ff2d9aa52efda76b5e010057e880942a6aac66d68b969e1f5f34a5a9cac95ba1
