# playbooks/yaml/argocd-apps/prowlarr/deployment.yaml
# Minimal Deployment for Prowlarr using linuxserver/prowlarr:1.34.1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media
  labels:
    app: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      initContainers:
        - name: seed-config
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              if [ ! -f /config/config.xml ]; then
                cp /template/config.xml /config/config.xml
              fi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config-template
              mountPath: /template
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr:1.34.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9696
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Pacific/Auckland"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
        - name: config-template
          configMap:
            name: prowlarr-initial-config
