apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr-initial-config
  namespace: media
  labels:
    app: prowlarr
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  config.xml: |-
    <Config>
      <BindAddress>*</BindAddress>
      <Port>9696</Port>
      <SslPort>6969</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>False</LaunchBrowser>
      <ApiKey>7057f5abbbbb4499a54941f51992a68c</ApiKey>
      <AuthenticationMethod>External</AuthenticationMethod>
      <AuthenticationRequired>Enabled</AuthenticationRequired>
      <Branch>master</Branch>
      <LogLevel>info</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase></UrlBase>
      <InstanceName>Prowlarr</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
    </Config>
