# playbooks/yaml/argocd-apps/prowlarr/prowlarr-application.yaml
# ArgoCD Application to manage Prowlarr
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/kpoxo6op/soyspray.git"
    targetRevision: "cinema"
    path: playbooks/yaml/argocd-apps/prowlarr
  destination:
    server: "https://kubernetes.default.svc"
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
