# playbooks/yaml/argocd-apps/longhorn/patches/csi-plugin-resources.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-csi-plugin
spec:
  template:
    spec:
      containers:
        - name: longhorn-csi-plugin
          resources:
            requests:
              cpu: "150m"
              memory: "200Mi"
            limits:
              cpu: "300m"
              memory: "400Mi"
