# playbooks/yaml/argocd-apps/longhorn/patches/csi-provisioner-resources.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-provisioner
spec:
  template:
    spec:
      containers:
        - name: csi-provisioner
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
