# playbooks/yaml/argocd-apps/longhorn/patches/ui-resources.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-ui
spec:
  template:
    spec:
      containers:
        - name: longhorn-ui
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "192Mi"
