# playbooks/argocd/apps/sonarr/pvc-config.yaml
# PersistentVolumeClaim for Sonarr configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
