apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-proxy-set-headers-qbittorrent
  namespace: media
data:
  X-Forwarded-Host: "$http_host"
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-server-qbittorrent
  namespace: media
spec:
  type: ExternalName
  externalName: authentik-server.authentik.svc.cluster.local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-authentik-outpost
  namespace: media
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - torrent.soyspray.vip
      secretName: prod-cert-tls
  rules:
    - host: torrent.soyspray.vip
      http:
        paths:
          - path: /outpost.goauthentik.io
            pathType: Prefix
            backend:
              service:
                name: authentik-server-qbittorrent
                port:
                  number: 80
