---
# Ensure proper node role labels for monitoring
- name: Ensure node labels
  hosts: kube_control_plane[0]
  gather_facts: false
  tasks:
    - name: Label control plane nodes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ item }}"
            labels:
              node-role.kubernetes.io/control-plane: control-plane
      loop: "{{ groups['kube_control_plane'] }}"

    - name: Label worker nodes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ item }}"
            labels:
              node-role.kubernetes.io/worker: worker
      loop: "{{ groups['kube_node'] | difference(groups['kube_control_plane']) }}"
