# Ansible Playbook: setup-local-volumes.yml
# Sets up local volumes for Local Static Storage Provisioner
- name: Common tasks for every playbook
  import_playbook: ../kubespray/playbooks/boilerplate.yml

- name: Setup local storage volumes
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Local Storage Setup Confirmation
      pause:
        prompt: "WARNING: This will modify /mnt/disks directory. Type 'yes' to continue."
      register: confirmation_prompt
      run_once: true
      when: not (skip_confirmation | default(false) | bool)

    - name: Check confirmation
      fail:
        msg: "Local storage setup cancelled by user"
      when:
        - not (skip_confirmation | default(false) | bool)
        - not confirmation_prompt.user_input | default("") == "yes"

  tasks:
    - name: Setup local volumes
      block:
        - name: Create volume directories
          file:
            path: "/mnt/disks/{{ item }}"
            state: directory
            mode: "0755"
            recurse: yes
          with_items: ["vol1"]
        - name: Setup bind mounts
          mount:
            path: "/mnt/disks/{{ item }}"
            src: "/mnt/disks/{{ item }}"
            fstype: none
            opts: bind
            state: mounted
          with_items: ["vol1"]
