# initialize-longhorn-storage.yml
#
# Ensures /storage is present, mounted, and ready for Longhorn on a single-node setup.
# Non-destructive: does NOT partition, format, or mount any disks. Assumes /storage is already mounted.
# Installs required packages and kernel modules for Longhorn.
# Safe to run multiple times.

- name: Common tasks for every playbook
  import_playbook: ../kubespray/playbooks/boilerplate.yml

- name: Prepare storage for Longhorn (single node, /storage only)
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Install required packages
      apt:
        name:
          - nfs-common
          - open-iscsi
          - cryptsetup
          - dmsetup
        state: present
        update_cache: yes

    - name: Ensure modules load on boot
      copy:
        dest: /etc/modules-load.d/longhorn.conf
        content: |
          iscsi_tcp
          dm_crypt
        mode: "0644"

    - name: Load kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - iscsi_tcp
        - dm_crypt

  tasks:
    - name: Ensure /storage directory exists
      file:
        path: /storage
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Check if /storage is mounted
      command: mountpoint /storage
      register: storage_mounted
      ignore_errors: true
      changed_when: false

    - name: Fail with friendly message if /storage is not mounted
      fail:
        msg: |
          /storage is NOT mounted!
          Please ensure /storage is mounted (e.g., via /etc/fstab) before running Longhorn.
          Example fstab entry:
            /dev/sdb1 /storage ext4 defaults 0 0
      when: storage_mounted.rc != 0

    - name: Display verification results
      debug:
        msg: |
          /storage is present and mounted:
          {{ storage_mounted.stdout }}
      when: storage_mounted.rc == 0
