# DEPRECATED: This playbook has been split into two separate playbooks:
# - clean-sda-devices.yml: For cleaning SDA devices for Longhorn
# - setup-local-volumes.yml: For setting up local volumes
#
# Please use those playbooks instead.

- name: Show deprecation warning
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display deprecation message
      fail:
        msg: |
          This playbook is deprecated.

          Please use instead:
          - ansible-playbook playbooks/clean-sda-devices.yml  # For cleaning SDA devices
          - ansible-playbook playbooks/setup-local-volumes.yml  # For local volume setup

          This playbook will be removed in future updates.
