# Ansible Playbook: prepare-local-storage.yml
# This playbook automates the preparation of local storage directories for the
# Local Static Storage Provisioner in Kubernetes.

- name: Common tasks for every playbook
  import_playbook: ../kubespray/playbooks/boilerplate.yml

- name: Prepare local storage for Local Static Provisioner
  hosts: all
  become: true
  gather_facts: true
  vars:
    local_volumes:
      - vol1
    local_storage_base_dir: /mnt/disks

  pre_tasks:
    - name: Storage Reset Confirmation
      pause:
        prompt: "This will delete all data in {{ local_storage_base_dir }}. Type 'yes' to continue."
      register: storage_confirmation_prompt
      run_once: true
      when: not (skip_confirmation | default(false) | bool)

    - name: Check confirmation
      fail:
        msg: "Storage cleanup cancelled by user"
      when:
        - not (skip_confirmation | default(false) | bool)
        - not storage_confirmation_prompt.user_input | default("") == "yes"

  tasks:
    - name: Ensure clean storage state
      block:
        - name: Unmount if mounted
          command: umount {{ local_storage_base_dir }}/{{ item }}
          with_items: "{{ local_volumes }}"
          ignore_errors: true

        - name: Remove old directory
          file:
            path: "{{ local_storage_base_dir }}"
            state: absent

    - name: Create and mount storage
      block:
        - name: Create volume directories
          file:
            path: "{{ local_storage_base_dir }}/{{ item }}"
            state: directory
            mode: '0755'
            recurse: yes
          with_items: "{{ local_volumes }}"

        - name: Setup bind mounts
          mount:
            path: "{{ local_storage_base_dir }}/{{ item }}"
            src: "{{ local_storage_base_dir }}/{{ item }}"
            fstype: none
            opts: bind
            state: mounted
          with_items: "{{ local_volumes }}"
