---
- name: Common tasks for every playbook
  import_playbook: kubespray/playbooks/boilerplate.yml

- name: Reboot all nodes in the cluster
  hosts: etcd:k8s_cluster:calico_rr
  gather_facts: false
  become: yes
  become_user: root
  serial: 1  # Reboot one node at a time to avoid full cluster downtime
 tasks:
    - name: Reboot the node
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 60
      tags: reboot
