---
# Cleanup playbook to remove the Flask test application
# This removes the test Flask server and cleans up all related files and configurations

- name: Common tasks for every playbook
  import_playbook: ../kubespray/playbooks/boilerplate.yml

- name: Remove Flask test application
  hosts: kube_control_plane[0]
  become: true
  vars:
    app_dir: /home/ubuntu/flask_test
    service_name: wireguard-test

  tasks:
    - name: Stop and disable the Flask service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: stopped
        enabled: no
      ignore_errors: true

    - name: Remove systemd service file
      ansible.builtin.file:
        path: "/etc/systemd/system/{{ service_name }}.service"
        state: absent

    - name: Reload systemd configuration
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Check if UFW is active
      ansible.builtin.command: ufw status
      register: ufw_status
      changed_when: false
      ignore_errors: true

    - name: Close port 5000 in UFW (if active)
      ansible.builtin.command: ufw delete allow 5000/tcp
      when: ufw_status.stdout is defined and "active" in ufw_status.stdout and "5000/tcp" in ufw_status.stdout
      ignore_errors: true

    - name: Remove Flask application directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: absent

    - name: Display cleanup results
      ansible.builtin.debug:
        msg:
          - "Flask test server has been successfully removed."
          - "All related files and configurations have been cleaned up."
