# playbooks/reboot.yml
# ansible-playbook playbooks/reboot.yml -e "node=node-2"
---
- name: Common tasks for every playbook
  import_playbook: ../kubespray/playbooks/boilerplate.yml

- name: Reboot a specific node in the cluster
  hosts: "{{ node | default('etcd:k8s_cluster:calico_rr') }}"
  gather_facts: true
  become: true
  become_user: root
  serial: 1
  tasks:

    - name: Drain (respect Longhorn replicas)
      shell: >
        kubectl drain {{ inventory_hostname }}
        --ignore-daemonsets
        --delete-emptydir-data
        --force
        --grace-period=30
        --disable-eviction=true
        --timeout={{ drain_timeout | default('10m') }}
      delegate_to: "{{ groups['kube_control_plane'][0] }}"
      register: drain_result
      retries: 3
      delay: 10
      until: drain_result.rc == 0
      tags: drain

    - name: Reboot
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: "{{ reboot_timeout | default(600) }}"
      tags: reboot

    - name: Wait for SSH
      wait_for_connection:
        delay: 10
        timeout: 300
      tags: uncordon

    - name: Wait for node to be Ready
      shell: |
        kubectl get node {{ inventory_hostname }} -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}'
      delegate_to: "{{ groups['kube_control_plane'][0] }}"
      register: node_ready
      retries: 30
      delay: 10
      until: node_ready.stdout == "True"
      tags: uncordon

    - name: Uncordon
      shell: kubectl uncordon {{ inventory_hostname }}
      delegate_to: "{{ groups['kube_control_plane'][0] }}"
      tags: uncordon
