---
# This playbook applies resource requests and limits to specific core components
# (MetalLB Speaker, Ingress Nginx Controller).
# On resource-constrained nodes (like the Celeron nodes in this cluster),
# pods without explicit requests/limits are often the first candidates for
# termination (e.g., OOM kills) or CPU throttling when the node is under pressure.
# Setting reasonable requests helps the Kubernetes scheduler place pods appropriately,
# and setting limits prevents them from consuming excessive resources.
# This aims to improve stability and reduce restarts for these components by making
# them more predictable to the Kubernetes resource management system.

# playbooks/apply-resource-limits.yml
- name: Apply Standard Resource Limits to Core Components
  hosts: kube_control_plane[0]
  become: true
  vars:
    kubeconfig_path: /etc/kubernetes/admin.conf
  tasks:
    - name: Apply resource limits to metallb speaker (DaemonSet)
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        kind: DaemonSet
        namespace: metallb-system
        name: speaker
        definition:
          spec:
            template:
              spec:
                containers:
                  - name: speaker
                    resources:
                      requests:
                        cpu: 50m
                        memory: 64Mi
                      limits:
                        cpu: 100m
                        memory: 128Mi

    - name: Apply resource limits to ingress-nginx controller (DaemonSet)
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        kind: DaemonSet
        namespace: ingress-nginx
        name: ingress-nginx-controller
        definition:
          spec:
            template:
              spec:
                containers:
                  - name: ingress-nginx-controller
                    resources:
                      requests:
                        cpu: 100m
                        memory: 128Mi
                      limits:
                        cpu: 500m
                        memory: 512Mi

