apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/kpoxo6op/soyspray.git"
    targetRevision: "HEAD"
    path: playbooks/yaml/argocd-apps/alert-test
  destination:
    server: "https://kubernetes.default.svc"
    namespace: alert-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

