all:
  hosts:
    node-0:
      ansible_host: 192.168.20.10
      ansible_user: ubuntu
      ip: 192.168.20.10
      access_ip: 192.168.20.10
      node_labels:
        node-role.kubernetes.io/worker: "true"
        soyspray.vip/longhorn-ssd: "true"
        soyspray.vip/local-media: "true"
    node-1:
      ansible_host: 192.168.20.11
      ansible_user: ubuntu
      ip: 192.168.20.11
      access_ip: 192.168.20.11
      node_labels:
        node-role.kubernetes.io/worker: "true"
        soyspray.vip/longhorn-ssd: "true"
    node-2:
      ansible_host: 192.168.20.12
      ansible_user: ubuntu
      ip: 192.168.20.12
      access_ip: 192.168.20.12
      node_labels:
        node-role.kubernetes.io/worker: "true"
        soyspray.vip/longhorn-ssd: "true"
  children:
    kube_control_plane:
      hosts:
        node-1:
        node-2:
        node-0:
    kube_node:
      hosts:
        node-1:
        node-2:
        node-0:
    etcd:
      hosts:
        node-1:
        node-2:
        node-0:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
