apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: logging
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: soyspray-observability
    app.kubernetes.io/version: "3.0.0"
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: info
    common:
      path_prefix: /var/loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks
    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    ruler:
      alertmanager_url: http://prometheus-kube-prometheus-alertmanager.monitoring.svc:9093
      evaluation_interval: 1m
      poll_interval: 30s
      ring:
        kvstore:
          store: inmemory
      rule_path: /etc/loki/rules
      storage:
        type: local
        local:
          directory: /etc/loki/rules
    compactor:
      working_directory: /var/loki/compactor
      shared_store: filesystem
      retention_enabled: true
    limits_config:
      retention_period: 720h
      reject_old_samples: true
      reject_old_samples_max_age: 744h
      max_cache_freshness_per_query: 10m
      max_global_streams_per_user: 15000
    chunk_store_config:
      max_look_back_period: 720h
    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h
    analytics:
      reporting_enabled: false
