apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: logging
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: soyspray-observability
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: 3100
    - name: grpc
      port: 9095
      targetPort: 9095
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: backend
