apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-postgres-data
  namespace: jira
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi
