apiVersion: v1
kind: Secret
metadata:
  name: jira-demo-secret
  namespace: jira
type: Opaque
stringData:
  postgres-user: jira
  postgres-password: jira-demo-postgres
  postgres-db: jira
  jira-username: demo
  jira-password: demo-password
  jira-email: demo@soyspray.vip
  jira-full-name: Demo User
