# playbooks/argocd/applications/home-automation/zigbee2mqtt/ingress.yaml
# Ingress for Zigbee2MQTT
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee2mqtt
  namespace: home-automation
  labels:
    app: zigbee2mqtt
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://authentik-server.authentik.svc.cluster.local/outpost.goauthentik.io/auth/nginx"
    nginx.ingress.kubernetes.io/auth-signin: "https://zigbee2mqtt.soyspray.vip/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid"
    nginx.ingress.kubernetes.io/auth-proxy-set-headers: "home-automation/auth-proxy-set-headers-zigbee2mqtt"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - zigbee2mqtt.soyspray.vip
      secretName: prod-cert-tls
  rules:
    - host: zigbee2mqtt.soyspray.vip
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zigbee2mqtt
                port:
                  number: 8080
