# playbooks/yaml/argocd-apps/lazylibrarian/lazylibrarian-application.yaml
# Argo CD Application manifest for LazyLibrarian

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lazylibrarian
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kpoxo6op/soyspray.git
    targetRevision: "v1.18.0"
    path: playbooks/yaml/argocd-apps/lazylibrarian
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
