# playbooks/yaml/argocd-apps/immich/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: immich
    version: 0.9.2
    repo: https://immich-app.github.io/immich-charts
    releaseName: immich
    valuesFile: values.yaml

resources:
  - immich-library-pvc.yaml

namespace: immich
