# playbooks/yaml/argocd-apps/immich/values.yaml
# Switch Immich to the external CNPG Postgres via DB_URL and explicitly select pgvecto.rs (vectors)
# Point Immich at the external Bitnami Redis service (standalone, no auth)
# Keep ML disabled, preserve your 2283 service/ingress, and disable the chart's internal Valkey
image:
  tag: v2.2.1

env:
  DB_URL: postgresql://immich:immich@immich-db-active.postgresql.svc.cluster.local:5432/immich
  DB_VECTOR_EXTENSION: "pgvecto.rs"
  REDIS_HOSTNAME: redis-master.redis.svc.cluster.local
  REDIS_PORT: "6379"
  IMMICH_MACHINE_LEARNING_URL: ""

server:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  service:
    main:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.36
      ports:
        http:
          port: 2283
  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich.soyspray.vip
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: prod-cert-tls
          hosts:
            - immich.soyspray.vip

machine-learning:
  enabled: false

immich:
  metrics:
    enabled: false
  persistence:
    library:
      existingClaim: immich-library
  configuration: {}

valkey:
  enabled: false
