# playbooks/yaml/argocd-apps/immich/values.yaml
image:
  tag: v1.131.3

# Override the templated environment variables with direct values
env:
  DB_HOSTNAME: postgresql.postgresql.svc.cluster.local
  DB_DATABASE_NAME: immich
  DB_USERNAME: immich
  DB_PASSWORD: immich
  REDIS_HOSTNAME: redis-master.redis.svc.cluster.local
  IMMICH_MACHINE_LEARNING_URL: ""

server:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  service:
    main:
      type: LoadBalancer
      loadBalancerIP: 192.168.50.208
      ports:
        http:
          port: 2283
  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich.soyspray.vip
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: prod-cert-tls
          hosts:
            - immich.soyspray.vip

machine-learning:
  enabled: false

immich:
  metrics:
    enabled: false
  persistence:
    library:
      existingClaim: immich-library
  configuration: {}

postgresql:
  # Turn off Immich's internal Postgres chart
  enabled: false

redis:
  # Turn off Immich's internal Redis chart
  enabled: false
